# Copyright (C) Andreas Karis <akaris@redhat.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# How to: 
# This will install pbench_agent on the undercloud and overcloud
# nodes.
#
# Adjust the list of hosts if needed. Then, execute:
# ansible-playbook -i /usr/bin/tripleo-ansible-inventory install_pbench.yml
#
# If nodes aren't registered yet, execute with:
# ansible-playbook -i /usr/bin/tripleo-ansible-inventory install_pbench.yml \
#     --extra-vars "(...) do_register=true org=<org-id> --activationkey=<activation key> (...)"
---
- hosts: [ overcloud, undercloud ] # change this if you want to be more granular
  become: true
  any_errors_fatal: true  # will need to implement better handling
  tasks:
  - debug:
      var: do_register
  - debug:
      var: activationkey
  - debug: 
      var: org
  - name: register
    redhat_subscription:
      state: present
      force_register: false
      org_id: "{{ org | default('undefined') }}"
      activationkey: "{{ activationkey | default('undefined') }}"
    when: do_register is defined and do_register|bool == true
  - name: enable repo rhel-7-server-optional-rpms 
    shell: 
      cmd: "subscription-manager repos --enable=rhel-7-server-optional-rpms"
  - name: install copr plugin
    yum:
      name: yum-plugin-copr
      state: latest
  - name: enable pbench repository
    shell:
      cmd: "yum copr enable ndokos/pbench -y"
  - name: install pbench-agent
    yum:
      name: pbench-agent
      state: latest
