# Copyright (C) Andreas Karis <akaris@redhat.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# How to: 
# This will uninstall pbench_agent on the undercloud and overcloud
# nodes.
#
# Adjust the list of hosts if needed. Then, execute:
# ansible-playbook -i /usr/bin/tripleo-ansible-inventory uninstall_pbench.yml
---
- hosts: 127.0.0.1 # change this if you want to be more granular
  become: true
  connection: local
  any_errors_fatal: true  # will need to implement better handling
  tasks:
  - name:  remove softlink for web-server static
    file:
      path: /opt/pbench-web-server/html/static
      state: absent
  - name:  create softlink for pbench-agent results
    file:
      path: /var/lib/pbench-agent
      state: absent
  - name: uninstall pbench-web-server
    yum:
      name: pbench-web-server
      state: absent
  - name: uninstall pbench-agent
    yum:
      name: pbench-agent
      state: absent
  - name: disable pbench repository
    ignore_errors: yes
    shell:
      cmd: "yum copr disable ndokos/pbench -y"
  - name: uninstall copr plugin
    yum:
      name: yum-plugin-copr
      state: absent
  - name:  remove /tmp/tools-default
    file:
      path: /tmp/tools-default
      state: absent
  - name:  remove /var/lib/pbench-agent
    file:
      path: /var/lib/pbench-agent
      state: absent
